# GUESS THE NUMBER GAME

print("""\n
""<< GUESS THE NUMBER >>""
THERE WILL BE A AUTOMATIC NUMBER ( 1- 6) GENERATED BY THE SYSTEM.
YOU HAVE TO GUESS THE NUMBER.
IF GUESS THE NUMBER CORRECTLY IN 3 OR LESS THAN 3 TRY -> IT MEANS "YOU WON
OTHERWISE YOU LOSE THE GAME

# to play again enter 1 otherwise enter any key

<< ALL THE BEST >>>\n\n""")

while True :
    import random
    a = random.randint(1,6)
    lst = [1,2,3,4,5,6]
    count = 0
    cd = 0
    for i in range(3) :
        cd += 1
        while True :
            try :
                while True :
                    b = int(input("Guess a number b/w 1 to 6 only => "))
                    if b in lst :
                        break
                    else :
                        print("##__please choose number from 1 to 6 only__##")
                break     
            except :
                print("##__INVALID NUMBER CHOOSEN__##")
        if a == b :
            count = 1
            print("<<<< CORRECTLY GUESSED >>>>")
            break
    if count == 1 :
        print("__________YOU WON_________")  
        print("The random number is => ",a)  
        print(f"You guessed correctly in {cd} number of try\n\n")    
    else :
        print("__________YOU LOSS_________") 
        print("The random number is => ",a)  
        print(f"You didn't guess correctly in 3 number of try\n\n")    

    c = input("WANT TO PLAY AGAIN => ")
    print()
    if c != "1" :    
        break
print("<<<<<HOPE YOU ENJOY THE GAME . THANK YOU FOR PLAYING THE GAME>>>>")  




